version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: banco-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  api:
    image: trabalho-sd:latest
    container_name: spring_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banco-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network: