CREATE TABLE tipoUsuario(
                            id INT GENERATED BY DEFAULT AS IDENTITY,
                            descricao VARCHAR(255) NOT NULL,
                            PRIMARY KEY(id)
);

CREATE TABLE usuario(
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        email VARCHAR(255) NOT NULL,
                        senha VARCHAR(255) NOT NULL,
                        nome VARCHAR(255) NOT NULL,
                        cpf VARCHAR(11) NOT NULL,
                        matricula_geral VARCHAR(50),
                        id_tipoUsuario INT REFERENCES tipoUsuario(id) NOT NULL,

                        PRIMARY KEY(id)
);

CREATE TABLE disciplina(
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           nome VARCHAR(255) NOT NULL,
                           id_professor BIGINT REFERENCES usuario(id) NOT NULL,

                            PRIMARY KEY(id)
);

CREATE TABLE matricula(
    id_aluno BIGINT REFERENCES usuario(id),
    id_disciplina BIGINT REFERENCES disciplina(id),
    status INT NOT NULL,
    PRIMARY KEY (id_aluno,id_disciplina)
);

CREATE TABLE prova(
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      id_disciplina BIGINT REFERENCES disciplina(id) NOT NULL,
                      titulo VARCHAR(100) NOT NULL,
                      descricao VARCHAR(255),
                      data DATE NOT NULL,
                      total_questoes INT NOT NULL,
                      ativa boolean DEFAULT FALSE,

                      PRIMARY KEY(id)

);

CREATE TABLE questao(
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        descricao TEXT NOT NULL,
                        id_prova BIGINT REFERENCES prova(id) NOT NULL,
                        alternativa_correta CHAR(1) NOT NULL,
                        alternativa_a VARCHAR(255) NOT NULL,
                        alternativa_b VARCHAR(255) NOT NULL,
                        alternativa_c VARCHAR(255) NOT NULL,
                        alternativa_d VARCHAR(255) NOT NULL,
                        alternativa_e VARCHAR(255) NOT NULL,

                        PRIMARY KEY(id)
);

CREATE TABLE resultadoAluno(
                                id_aluno BIGINT REFERENCES usuario(id) NOT NULL,
                                id_questao BIGINT REFERENCES questao(id) NOT NULL,
                                resposta_aluno CHAR(1) NOT NULL,
                                acertou BOOLEAN NOT NULL,
                                PRIMARY KEY(id_aluno,id_questao)
);